// Generated by Bisonc++ V2.09.03 on Sat, 08 Mar 2014 22:55:05 +0530

// $insert class.ih
#include "parser.ih"

// The FIRST element of SR arrays shown below uses `d_type', defining the
// state's type, and `d_lastIdx' containing the last element's index. If
// d_lastIdx contains the REQ_TOKEN bitflag (see below) then the state needs
// a token: if in this state d_token__ is _UNDETERMINED_, nextToken() will be
// called

// The LAST element of SR arrays uses `d_token' containing the last retrieved
// token to speed up the (linear) seach.  Except for the first element of SR
// arrays, the field `d_action' is used to determine what to do next. If
// positive, it represents the next state (used with SHIFT); if zero, it
// indicates `ACCEPT', if negative, -d_action represents the number of the
// rule to reduce to.

// `lookup()' tries to find d_token__ in the current SR array. If it fails, and
// there is no default reduction UNEXPECTED_TOKEN__ is thrown, which is then
// caught by the error-recovery function.

// The error-recovery function will pop elements off the stack until a state
// having bit flag ERR_ITEM is found. This state has a transition on _error_
// which is applied. In this _error_ state, while the current token is not a
// proper continuation, new tokens are obtained by nextToken(). If such a
// token is found, error recovery is successful and the token is
// handled according to the error state's SR table and parsing continues.
// During error recovery semantic actions are ignored.

// A state flagged with the DEF_RED flag will perform a default
// reduction if no other continuations are available for the current token.

// The ACCEPT STATE never shows a default reduction: when it is reached the
// parser returns ACCEPT(). During the grammar
// analysis phase a default reduction may have been defined, but it is
// removed during the state-definition phase.

// So:
//      s_x[] = 
//      {
//                  [_field_1_]         [_field_2_]
//
// First element:   {state-type,        idx of last element},
// Other elements:  {required token,    action to perform},
//                                      ( < 0: reduce, 
//                                          0: ACCEPT,
//                                        > 0: next state)
// Last element:    {set to d_token__,    action to perform}
//      }

// When the --thread-safe option is specified, all static data are defined as
// const. If --thread-safe is not provided, the state-tables are not defined
// as const, since the lookup() function below will modify them


namespace // anonymous
{
    char const author[] = "Frank B. Brokken (f.b.brokken@rug.nl)";

    enum 
    {
        STACK_EXPANSION = 5     // size to expand the state-stack with when
                                // full
    };

    enum ReservedTokens
    {
        PARSE_ACCEPT     = 0,   // `ACCEPT' TRANSITION
        _UNDETERMINED_   = -2,
        _EOF_            = -1,
        _error_          = 256
    };
    enum StateType       // modify statetype/data.cc when this enum changes
    {
        NORMAL,
        ERR_ITEM,
        REQ_TOKEN,
        ERR_REQ,    // ERR_ITEM | REQ_TOKEN
        DEF_RED,    // state having default reduction
        ERR_DEF,    // ERR_ITEM | DEF_RED
        REQ_DEF,    // REQ_TOKEN | DEF_RED
        ERR_REQ_DEF // ERR_ITEM | REQ_TOKEN | DEF_RED
    };    
    struct PI__     // Production Info
    {
        size_t d_nonTerm; // identification number of this production's
                            // non-terminal 
        size_t d_size;    // number of elements in this production 
    };

    struct SR__     // Shift Reduce info, see its description above
    {
        union
        {
            int _field_1_;      // initializer, allowing initializations 
                                // of the SR s_[] arrays
            int d_type;
            int d_token;
        };
        union
        {
            int _field_2_;

            int d_lastIdx;          // if negative, the state uses SHIFT
            int d_action;           // may be negative (reduce), 
                                    // postive (shift), or 0 (accept)
            size_t d_errorState;    // used with Error states
        };
    };

    // $insert staticdata
    
// Productions Info Records:
PI__ const s_productionInfo[] = 
{
     {0, 0}, // not used: reduction values are negative
     {294, 4}, // 1: program ->  variable_declaration_statement_list function_declaration_statement_list #0001 procedure_list
     {297, 0}, // 2: #0001 ->  <empty>
     {294, 3}, // 3: program ->  variable_declaration_statement_list #0002 procedure_list
     {298, 0}, // 4: #0002 ->  <empty>
     {294, 2}, // 5: program ->  function_declaration_statement_list procedure_list
     {294, 1}, // 6: program ->  procedure_list
     {296, 2}, // 7: procedure_list ->  procedure_name procedure_body
     {296, 3}, // 8: procedure_list ->  procedure_list procedure_name procedure_body
     {299, 4}, // 9: procedure_name (NAME) ->  NAME '(' function_parameter_list ')'
     {299, 3}, // 10: procedure_name (NAME) ->  NAME '(' ')'
     {300, 5}, // 11: procedure_body ('{') ->  '{' variable_declaration_statement_list #0003 basic_block_list '}'
     {301, 0}, // 12: #0003 ->  <empty>
     {300, 3}, // 13: procedure_body ('{') ->  '{' basic_block_list '}'
     {295, 1}, // 14: function_declaration_statement_list ->  function_declaration_statement
     {295, 2}, // 15: function_declaration_statement_list ->  function_declaration_statement_list function_declaration_statement
     {303, 1}, // 16: variable_declaration_statement_list ->  variable_declaration_statement
     {303, 2}, // 17: variable_declaration_statement_list ->  variable_declaration_statement_list variable_declaration_statement
     {304, 3}, // 18: variable_declaration_statement (INTEGER) ->  INTEGER NAME ';'
     {304, 3}, // 19: variable_declaration_statement (FLOAT) ->  FLOAT NAME ';'
     {304, 3}, // 20: variable_declaration_statement (DOUBLE) ->  DOUBLE NAME ';'
     {302, 6}, // 21: function_declaration_statement (VOID) ->  VOID NAME '(' function_parameter_list ')' ';'
     {302, 5}, // 22: function_declaration_statement (VOID) ->  VOID NAME '(' ')' ';'
     {302, 6}, // 23: function_declaration_statement (INTEGER) ->  INTEGER NAME '(' function_parameter_list ')' ';'
     {302, 5}, // 24: function_declaration_statement (INTEGER) ->  INTEGER NAME '(' ')' ';'
     {302, 6}, // 25: function_declaration_statement (FLOAT) ->  FLOAT NAME '(' function_parameter_list ')' ';'
     {302, 5}, // 26: function_declaration_statement (FLOAT) ->  FLOAT NAME '(' ')' ';'
     {302, 6}, // 27: function_declaration_statement (DOUBLE) ->  DOUBLE NAME '(' function_parameter_list ')' ';'
     {302, 5}, // 28: function_declaration_statement (DOUBLE) ->  DOUBLE NAME '(' ')' ';'
     {305, 1}, // 29: function_parameter_list ->  function_parameter
     {305, 3}, // 30: function_parameter_list (',') ->  function_parameter_list ',' function_parameter
     {306, 2}, // 31: function_parameter (INTEGER) ->  INTEGER NAME
     {306, 2}, // 32: function_parameter (FLOAT) ->  FLOAT NAME
     {306, 2}, // 33: function_parameter (DOUBLE) ->  DOUBLE NAME
     {307, 2}, // 34: basic_block_list ->  basic_block_list basic_block
     {307, 1}, // 35: basic_block_list ->  basic_block
     {308, 3}, // 36: basic_block (BASIC_BLOCK) ->  BASIC_BLOCK ':' executable_statement_list
     {309, 2}, // 37: return_statement (RETURN) ->  RETURN ';'
     {309, 3}, // 38: return_statement (RETURN) ->  RETURN relational_statement ';'
     {310, 1}, // 39: executable_statement_list ->  assignment_statement
     {310, 2}, // 40: executable_statement_list (';') ->  function_call ';'
     {310, 2}, // 41: executable_statement_list ->  assignment_statement executable_statement_list
     {310, 3}, // 42: executable_statement_list (';') ->  function_call ';' executable_statement_list
     {310, 1}, // 43: executable_statement_list ->  return_statement
     {310, 1}, // 44: executable_statement_list ->  if_statement
     {310, 1}, // 45: executable_statement_list ->  goto_statement
     {311, 4}, // 46: function_call (NAME) ->  NAME '(' function_argument_list ')'
     {311, 3}, // 47: function_call (NAME) ->  NAME '(' ')'
     {312, 1}, // 48: function_argument_list ->  function_argument
     {312, 3}, // 49: function_argument_list (',') ->  function_argument_list ',' function_argument
     {313, 1}, // 50: function_argument ->  relational_statement
     {314, 7}, // 51: if_statement (IF) ->  IF '(' relational_statement ')' goto_statement ELSE goto_statement
     {315, 3}, // 52: goto_statement (GOTO) ->  GOTO BASIC_BLOCK ';'
     {316, 1}, // 53: relational_statement ->  arithmetic_expression
     {316, 3}, // 54: relational_statement (le) ->  relational_statement le relational_statement
     {316, 3}, // 55: relational_statement (ge) ->  relational_statement ge relational_statement
     {316, 3}, // 56: relational_statement (gt) ->  relational_statement gt relational_statement
     {316, 3}, // 57: relational_statement (lt) ->  relational_statement lt relational_statement
     {316, 3}, // 58: relational_statement (eq) ->  relational_statement eq relational_statement
     {316, 3}, // 59: relational_statement (ne) ->  relational_statement ne relational_statement
     {317, 1}, // 60: arithmetic_expression ->  constant
     {317, 1}, // 61: arithmetic_expression ->  variable
     {317, 1}, // 62: arithmetic_expression ->  function_call
     {317, 3}, // 63: arithmetic_expression ('(') ->  '(' relational_statement ')'
     {317, 4}, // 64: arithmetic_expression ('(') ->  '(' FLOAT ')' function_call
     {317, 4}, // 65: arithmetic_expression ('(') ->  '(' INTEGER ')' function_call
     {317, 4}, // 66: arithmetic_expression ('(') ->  '(' DOUBLE ')' function_call
     {317, 4}, // 67: arithmetic_expression ('(') ->  '(' FLOAT ')' variable
     {317, 4}, // 68: arithmetic_expression ('(') ->  '(' INTEGER ')' variable
     {317, 4}, // 69: arithmetic_expression ('(') ->  '(' DOUBLE ')' variable
     {317, 6}, // 70: arithmetic_expression ('(') ->  '(' INTEGER ')' '(' arithmetic_expression ')'
     {317, 6}, // 71: arithmetic_expression ('(') ->  '(' FLOAT ')' '(' relational_statement ')'
     {317, 6}, // 72: arithmetic_expression ('(') ->  '(' DOUBLE ')' '(' relational_statement ')'
     {317, 2}, // 73: arithmetic_expression ('-') ->  '-' arithmetic_expression
     {317, 3}, // 74: arithmetic_expression ('+') ->  arithmetic_expression '+' arithmetic_expression
     {317, 3}, // 75: arithmetic_expression ('-') ->  arithmetic_expression '-' arithmetic_expression
     {317, 3}, // 76: arithmetic_expression ('*') ->  arithmetic_expression '*' arithmetic_expression
     {317, 3}, // 77: arithmetic_expression ('/') ->  arithmetic_expression '/' arithmetic_expression
     {318, 4}, // 78: assignment_statement (ASSIGN_OP) ->  variable ASSIGN_OP relational_statement ';'
     {319, 1}, // 79: variable (NAME) ->  NAME
     {320, 1}, // 80: constant (INTEGER_NUMBER) ->  INTEGER_NUMBER
     {320, 1}, // 81: constant (FLOAT_NUMBER) ->  FLOAT_NUMBER
     {321, 1}, // 82: program_$ ->  program
};

// State info and SR__ transitions for each state.


SR__ s_0[] =
{
    { { REQ_TOKEN}, { 13} },                                       
    { {       294}, {  1} }, // program                            
    { {       303}, {  2} }, // variable_declaration_statement_list
    { {       295}, {  3} }, // function_declaration_statement_list
    { {       296}, {  4} }, // procedure_list                     
    { {       304}, {  5} }, // variable_declaration_statement     
    { {       302}, {  6} }, // function_declaration_statement     
    { {       299}, {  7} }, // procedure_name                     
    { {       262}, {  8} }, // INTEGER                            
    { {       263}, {  9} }, // FLOAT                              
    { {       264}, { 10} }, // DOUBLE                             
    { {       265}, { 11} }, // VOID                               
    { {       260}, { 12} }, // NAME                               
    { {         0}, {  0} },                                       
};

SR__ s_1[] =
{
    { { REQ_TOKEN}, {            2} }, 
    { {     _EOF_}, { PARSE_ACCEPT} }, 
    { {         0}, {            0} }, 
};

SR__ s_2[] =
{
    { { REQ_DEF}, {  9} },                                       
    { {     295}, { 13} }, // function_declaration_statement_list
    { {     298}, { 14} }, // #0002                              
    { {     304}, { 15} }, // variable_declaration_statement     
    { {     302}, {  6} }, // function_declaration_statement     
    { {     262}, {  8} }, // INTEGER                            
    { {     263}, {  9} }, // FLOAT                              
    { {     264}, { 10} }, // DOUBLE                             
    { {     265}, { 11} }, // VOID                               
    { {       0}, { -4} },                                       
};

SR__ s_3[] =
{
    { { REQ_TOKEN}, {  9} },                                  
    { {       296}, { 16} }, // procedure_list                
    { {       302}, { 17} }, // function_declaration_statement
    { {       299}, {  7} }, // procedure_name                
    { {       265}, { 11} }, // VOID                          
    { {       262}, { 18} }, // INTEGER                       
    { {       263}, { 19} }, // FLOAT                         
    { {       264}, { 20} }, // DOUBLE                        
    { {       260}, { 12} }, // NAME                          
    { {         0}, {  0} },                                  
};

SR__ s_4[] =
{
    { { REQ_DEF}, {  3} },                  
    { {     299}, { 21} }, // procedure_name
    { {     260}, { 12} }, // NAME          
    { {       0}, { -6} },                  
};

SR__ s_5[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -16} }, 
};

SR__ s_6[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -14} }, 
};

SR__ s_7[] =
{
    { { REQ_TOKEN}, {  3} },                  
    { {       300}, { 22} }, // procedure_body
    { {       123}, { 23} }, // '{'           
    { {         0}, {  0} },                  
};

SR__ s_8[] =
{
    { { REQ_TOKEN}, {  2} },        
    { {       260}, { 24} }, // NAME
    { {         0}, {  0} },        
};

SR__ s_9[] =
{
    { { REQ_TOKEN}, {  2} },        
    { {       260}, { 25} }, // NAME
    { {         0}, {  0} },        
};

SR__ s_10[] =
{
    { { REQ_TOKEN}, {  2} },        
    { {       260}, { 26} }, // NAME
    { {         0}, {  0} },        
};

SR__ s_11[] =
{
    { { REQ_TOKEN}, {  2} },        
    { {       260}, { 27} }, // NAME
    { {         0}, {  0} },        
};

SR__ s_12[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        40}, { 28} }, // '('
    { {         0}, {  0} },       
};

SR__ s_13[] =
{
    { { REQ_DEF}, {  7} },                                  
    { {     297}, { 29} }, // #0001                         
    { {     302}, { 17} }, // function_declaration_statement
    { {     265}, { 11} }, // VOID                          
    { {     262}, { 18} }, // INTEGER                       
    { {     263}, { 19} }, // FLOAT                         
    { {     264}, { 20} }, // DOUBLE                        
    { {       0}, { -2} },                                  
};

SR__ s_14[] =
{
    { { REQ_TOKEN}, {  4} },                  
    { {       296}, { 30} }, // procedure_list
    { {       299}, {  7} }, // procedure_name
    { {       260}, { 12} }, // NAME          
    { {         0}, {  0} },                  
};

SR__ s_15[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -17} }, 
};

SR__ s_16[] =
{
    { { REQ_DEF}, {  3} },                  
    { {     299}, { 21} }, // procedure_name
    { {     260}, { 12} }, // NAME          
    { {       0}, { -5} },                  
};

SR__ s_17[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -15} }, 
};

SR__ s_18[] =
{
    { { REQ_TOKEN}, {  2} },        
    { {       260}, { 31} }, // NAME
    { {         0}, {  0} },        
};

SR__ s_19[] =
{
    { { REQ_TOKEN}, {  2} },        
    { {       260}, { 32} }, // NAME
    { {         0}, {  0} },        
};

SR__ s_20[] =
{
    { { REQ_TOKEN}, {  2} },        
    { {       260}, { 33} }, // NAME
    { {         0}, {  0} },        
};

SR__ s_21[] =
{
    { { REQ_TOKEN}, {  3} },                  
    { {       300}, { 34} }, // procedure_body
    { {       123}, { 23} }, // '{'           
    { {         0}, {  0} },                  
};

SR__ s_22[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -7} }, 
};

SR__ s_23[] =
{
    { { REQ_TOKEN}, {  9} },                                       
    { {       303}, { 35} }, // variable_declaration_statement_list
    { {       307}, { 36} }, // basic_block_list                   
    { {       304}, {  5} }, // variable_declaration_statement     
    { {       308}, { 37} }, // basic_block                        
    { {       262}, { 38} }, // INTEGER                            
    { {       263}, { 39} }, // FLOAT                              
    { {       264}, { 40} }, // DOUBLE                             
    { {       258}, { 41} }, // BASIC_BLOCK                        
    { {         0}, {  0} },                                       
};

SR__ s_24[] =
{
    { { REQ_TOKEN}, {  3} },       
    { {        59}, { 42} }, // ';'
    { {        40}, { 43} }, // '('
    { {         0}, {  0} },       
};

SR__ s_25[] =
{
    { { REQ_TOKEN}, {  3} },       
    { {        59}, { 44} }, // ';'
    { {        40}, { 45} }, // '('
    { {         0}, {  0} },       
};

SR__ s_26[] =
{
    { { REQ_TOKEN}, {  3} },       
    { {        59}, { 46} }, // ';'
    { {        40}, { 47} }, // '('
    { {         0}, {  0} },       
};

SR__ s_27[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        40}, { 48} }, // '('
    { {         0}, {  0} },       
};

SR__ s_28[] =
{
    { { REQ_TOKEN}, {  7} },                           
    { {       305}, { 49} }, // function_parameter_list
    { {        41}, { 50} }, // ')'                    
    { {       306}, { 51} }, // function_parameter     
    { {       262}, { 52} }, // INTEGER                
    { {       263}, { 53} }, // FLOAT                  
    { {       264}, { 54} }, // DOUBLE                 
    { {         0}, {  0} },                           
};

SR__ s_29[] =
{
    { { REQ_TOKEN}, {  4} },                  
    { {       296}, { 55} }, // procedure_list
    { {       299}, {  7} }, // procedure_name
    { {       260}, { 12} }, // NAME          
    { {         0}, {  0} },                  
};

SR__ s_30[] =
{
    { { REQ_DEF}, {  3} },                  
    { {     299}, { 21} }, // procedure_name
    { {     260}, { 12} }, // NAME          
    { {       0}, { -3} },                  
};

SR__ s_31[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        40}, { 43} }, // '('
    { {         0}, {  0} },       
};

SR__ s_32[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        40}, { 45} }, // '('
    { {         0}, {  0} },       
};

SR__ s_33[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        40}, { 47} }, // '('
    { {         0}, {  0} },       
};

SR__ s_34[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -8} }, 
};

SR__ s_35[] =
{
    { { REQ_DEF}, {   6} },                                  
    { {     301}, {  56} }, // #0003                         
    { {     304}, {  15} }, // variable_declaration_statement
    { {     262}, {  38} }, // INTEGER                       
    { {     263}, {  39} }, // FLOAT                         
    { {     264}, {  40} }, // DOUBLE                        
    { {       0}, { -12} },                                  
};

SR__ s_36[] =
{
    { { REQ_TOKEN}, {  4} },               
    { {       125}, { 57} }, // '}'        
    { {       308}, { 58} }, // basic_block
    { {       258}, { 41} }, // BASIC_BLOCK
    { {         0}, {  0} },               
};

SR__ s_37[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -35} }, 
};

SR__ s_38[] =
{
    { { REQ_TOKEN}, {  2} },        
    { {       260}, { 59} }, // NAME
    { {         0}, {  0} },        
};

SR__ s_39[] =
{
    { { REQ_TOKEN}, {  2} },        
    { {       260}, { 60} }, // NAME
    { {         0}, {  0} },        
};

SR__ s_40[] =
{
    { { REQ_TOKEN}, {  2} },        
    { {       260}, { 61} }, // NAME
    { {         0}, {  0} },        
};

SR__ s_41[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        58}, { 62} }, // ':'
    { {         0}, {  0} },       
};

SR__ s_42[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -18} }, 
};

SR__ s_43[] =
{
    { { REQ_TOKEN}, {  7} },                           
    { {       305}, { 63} }, // function_parameter_list
    { {        41}, { 64} }, // ')'                    
    { {       306}, { 51} }, // function_parameter     
    { {       262}, { 52} }, // INTEGER                
    { {       263}, { 53} }, // FLOAT                  
    { {       264}, { 54} }, // DOUBLE                 
    { {         0}, {  0} },                           
};

SR__ s_44[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -19} }, 
};

SR__ s_45[] =
{
    { { REQ_TOKEN}, {  7} },                           
    { {       305}, { 65} }, // function_parameter_list
    { {        41}, { 66} }, // ')'                    
    { {       306}, { 51} }, // function_parameter     
    { {       262}, { 52} }, // INTEGER                
    { {       263}, { 53} }, // FLOAT                  
    { {       264}, { 54} }, // DOUBLE                 
    { {         0}, {  0} },                           
};

SR__ s_46[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -20} }, 
};

SR__ s_47[] =
{
    { { REQ_TOKEN}, {  7} },                           
    { {       305}, { 67} }, // function_parameter_list
    { {        41}, { 68} }, // ')'                    
    { {       306}, { 51} }, // function_parameter     
    { {       262}, { 52} }, // INTEGER                
    { {       263}, { 53} }, // FLOAT                  
    { {       264}, { 54} }, // DOUBLE                 
    { {         0}, {  0} },                           
};

SR__ s_48[] =
{
    { { REQ_TOKEN}, {  7} },                           
    { {       305}, { 69} }, // function_parameter_list
    { {        41}, { 70} }, // ')'                    
    { {       306}, { 51} }, // function_parameter     
    { {       262}, { 52} }, // INTEGER                
    { {       263}, { 53} }, // FLOAT                  
    { {       264}, { 54} }, // DOUBLE                 
    { {         0}, {  0} },                           
};

SR__ s_49[] =
{
    { { REQ_TOKEN}, {  3} },       
    { {        41}, { 71} }, // ')'
    { {        44}, { 72} }, // ','
    { {         0}, {  0} },       
};

SR__ s_50[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -10} }, 
};

SR__ s_51[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -29} }, 
};

SR__ s_52[] =
{
    { { REQ_TOKEN}, {  2} },        
    { {       260}, { 73} }, // NAME
    { {         0}, {  0} },        
};

SR__ s_53[] =
{
    { { REQ_TOKEN}, {  2} },        
    { {       260}, { 74} }, // NAME
    { {         0}, {  0} },        
};

SR__ s_54[] =
{
    { { REQ_TOKEN}, {  2} },        
    { {       260}, { 75} }, // NAME
    { {         0}, {  0} },        
};

SR__ s_55[] =
{
    { { REQ_DEF}, {  3} },                  
    { {     299}, { 21} }, // procedure_name
    { {     260}, { 12} }, // NAME          
    { {       0}, { -1} },                  
};

SR__ s_56[] =
{
    { { REQ_TOKEN}, {  4} },                    
    { {       307}, { 76} }, // basic_block_list
    { {       308}, { 37} }, // basic_block     
    { {       258}, { 41} }, // BASIC_BLOCK     
    { {         0}, {  0} },                    
};

SR__ s_57[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -13} }, 
};

SR__ s_58[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -34} }, 
};

SR__ s_59[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        59}, { 42} }, // ';'
    { {         0}, {  0} },       
};

SR__ s_60[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        59}, { 44} }, // ';'
    { {         0}, {  0} },       
};

SR__ s_61[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        59}, { 46} }, // ';'
    { {         0}, {  0} },       
};

SR__ s_62[] =
{
    { { REQ_TOKEN}, { 12} },                             
    { {       310}, { 77} }, // executable_statement_list
    { {       318}, { 78} }, // assignment_statement     
    { {       311}, { 79} }, // function_call            
    { {       309}, { 80} }, // return_statement         
    { {       314}, { 81} }, // if_statement             
    { {       315}, { 82} }, // goto_statement           
    { {       319}, { 83} }, // variable                 
    { {       260}, { 84} }, // NAME                     
    { {       261}, { 85} }, // RETURN                   
    { {       266}, { 86} }, // IF                       
    { {       268}, { 87} }, // GOTO                     
    { {         0}, {  0} },                             
};

SR__ s_63[] =
{
    { { REQ_TOKEN}, {  3} },       
    { {        41}, { 88} }, // ')'
    { {        44}, { 72} }, // ','
    { {         0}, {  0} },       
};

SR__ s_64[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        59}, { 89} }, // ';'
    { {         0}, {  0} },       
};

SR__ s_65[] =
{
    { { REQ_TOKEN}, {  3} },       
    { {        41}, { 90} }, // ')'
    { {        44}, { 72} }, // ','
    { {         0}, {  0} },       
};

SR__ s_66[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        59}, { 91} }, // ';'
    { {         0}, {  0} },       
};

SR__ s_67[] =
{
    { { REQ_TOKEN}, {  3} },       
    { {        41}, { 92} }, // ')'
    { {        44}, { 72} }, // ','
    { {         0}, {  0} },       
};

SR__ s_68[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        59}, { 93} }, // ';'
    { {         0}, {  0} },       
};

SR__ s_69[] =
{
    { { REQ_TOKEN}, {  3} },       
    { {        41}, { 94} }, // ')'
    { {        44}, { 72} }, // ','
    { {         0}, {  0} },       
};

SR__ s_70[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        59}, { 95} }, // ';'
    { {         0}, {  0} },       
};

SR__ s_71[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -9} }, 
};

SR__ s_72[] =
{
    { { REQ_TOKEN}, {  5} },                      
    { {       306}, { 96} }, // function_parameter
    { {       262}, { 52} }, // INTEGER           
    { {       263}, { 53} }, // FLOAT             
    { {       264}, { 54} }, // DOUBLE            
    { {         0}, {  0} },                      
};

SR__ s_73[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -31} }, 
};

SR__ s_74[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -32} }, 
};

SR__ s_75[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -33} }, 
};

SR__ s_76[] =
{
    { { REQ_TOKEN}, {  4} },               
    { {       125}, { 97} }, // '}'        
    { {       308}, { 58} }, // basic_block
    { {       258}, { 41} }, // BASIC_BLOCK
    { {         0}, {  0} },               
};

SR__ s_77[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -36} }, 
};

SR__ s_78[] =
{
    { { REQ_DEF}, {  12} },                             
    { {     310}, {  98} }, // executable_statement_list
    { {     318}, {  78} }, // assignment_statement     
    { {     311}, {  79} }, // function_call            
    { {     309}, {  80} }, // return_statement         
    { {     314}, {  81} }, // if_statement             
    { {     315}, {  82} }, // goto_statement           
    { {     319}, {  83} }, // variable                 
    { {     260}, {  84} }, // NAME                     
    { {     261}, {  85} }, // RETURN                   
    { {     266}, {  86} }, // IF                       
    { {     268}, {  87} }, // GOTO                     
    { {       0}, { -39} },                             
};

SR__ s_79[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        59}, { 99} }, // ';'
    { {         0}, {  0} },       
};

SR__ s_80[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -43} }, 
};

SR__ s_81[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -44} }, 
};

SR__ s_82[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -45} }, 
};

SR__ s_83[] =
{
    { { REQ_TOKEN}, {   2} },             
    { {       269}, { 100} }, // ASSIGN_OP
    { {         0}, {   0} },             
};

SR__ s_84[] =
{
    { { REQ_DEF}, {   2} },       
    { {      40}, { 101} }, // '('
    { {       0}, { -79} },       
};

SR__ s_85[] =
{
    { { REQ_TOKEN}, {  12} },                         
    { {        59}, { 102} }, // ';'                  
    { {       316}, { 103} }, // relational_statement 
    { {       317}, { 104} }, // arithmetic_expression
    { {       320}, { 105} }, // constant             
    { {       319}, { 106} }, // variable             
    { {       311}, { 107} }, // function_call        
    { {        40}, { 108} }, // '('                  
    { {        45}, { 109} }, // '-'                  
    { {       257}, { 110} }, // INTEGER_NUMBER       
    { {       259}, { 111} }, // FLOAT_NUMBER         
    { {       260}, {  84} }, // NAME                 
    { {         0}, {   0} },                         
};

SR__ s_86[] =
{
    { { REQ_TOKEN}, {   2} },       
    { {        40}, { 112} }, // '('
    { {         0}, {   0} },       
};

SR__ s_87[] =
{
    { { REQ_TOKEN}, {   2} },               
    { {       258}, { 113} }, // BASIC_BLOCK
    { {         0}, {   0} },               
};

SR__ s_88[] =
{
    { { REQ_TOKEN}, {   2} },       
    { {        59}, { 114} }, // ';'
    { {         0}, {   0} },       
};

SR__ s_89[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -24} }, 
};

SR__ s_90[] =
{
    { { REQ_TOKEN}, {   2} },       
    { {        59}, { 115} }, // ';'
    { {         0}, {   0} },       
};

SR__ s_91[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -26} }, 
};

SR__ s_92[] =
{
    { { REQ_TOKEN}, {   2} },       
    { {        59}, { 116} }, // ';'
    { {         0}, {   0} },       
};

SR__ s_93[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -28} }, 
};

SR__ s_94[] =
{
    { { REQ_TOKEN}, {   2} },       
    { {        59}, { 117} }, // ';'
    { {         0}, {   0} },       
};

SR__ s_95[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -22} }, 
};

SR__ s_96[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -30} }, 
};

SR__ s_97[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -11} }, 
};

SR__ s_98[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -41} }, 
};

SR__ s_99[] =
{
    { { REQ_DEF}, {  12} },                             
    { {     310}, { 118} }, // executable_statement_list
    { {     318}, {  78} }, // assignment_statement     
    { {     311}, {  79} }, // function_call            
    { {     309}, {  80} }, // return_statement         
    { {     314}, {  81} }, // if_statement             
    { {     315}, {  82} }, // goto_statement           
    { {     319}, {  83} }, // variable                 
    { {     260}, {  84} }, // NAME                     
    { {     261}, {  85} }, // RETURN                   
    { {     266}, {  86} }, // IF                       
    { {     268}, {  87} }, // GOTO                     
    { {       0}, { -40} },                             
};

SR__ s_100[] =
{
    { { REQ_TOKEN}, {  11} },                         
    { {       316}, { 119} }, // relational_statement 
    { {       317}, { 104} }, // arithmetic_expression
    { {       320}, { 105} }, // constant             
    { {       319}, { 106} }, // variable             
    { {       311}, { 107} }, // function_call        
    { {        40}, { 108} }, // '('                  
    { {        45}, { 109} }, // '-'                  
    { {       257}, { 110} }, // INTEGER_NUMBER       
    { {       259}, { 111} }, // FLOAT_NUMBER         
    { {       260}, {  84} }, // NAME                 
    { {         0}, {   0} },                         
};

SR__ s_101[] =
{
    { { REQ_TOKEN}, {  14} },                          
    { {       312}, { 120} }, // function_argument_list
    { {        41}, { 121} }, // ')'                   
    { {       313}, { 122} }, // function_argument     
    { {       316}, { 123} }, // relational_statement  
    { {       317}, { 104} }, // arithmetic_expression 
    { {       320}, { 105} }, // constant              
    { {       319}, { 106} }, // variable              
    { {       311}, { 107} }, // function_call         
    { {        40}, { 108} }, // '('                   
    { {        45}, { 109} }, // '-'                   
    { {       257}, { 110} }, // INTEGER_NUMBER        
    { {       259}, { 111} }, // FLOAT_NUMBER          
    { {       260}, {  84} }, // NAME                  
    { {         0}, {   0} },                          
};

SR__ s_102[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -37} }, 
};

SR__ s_103[] =
{
    { { REQ_TOKEN}, {   8} },       
    { {        59}, { 124} }, // ';'
    { {       273}, { 125} }, // le 
    { {       275}, { 126} }, // ge 
    { {       274}, { 127} }, // gt 
    { {       272}, { 128} }, // lt 
    { {       271}, { 129} }, // eq 
    { {       270}, { 130} }, // ne 
    { {         0}, {   0} },       
};

SR__ s_104[] =
{
    { { REQ_DEF}, {   5} },       
    { {      43}, { 131} }, // '+'
    { {      45}, { 132} }, // '-'
    { {      42}, { 133} }, // '*'
    { {      47}, { 134} }, // '/'
    { {       0}, { -53} },       
};

SR__ s_105[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -60} }, 
};

SR__ s_106[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -61} }, 
};

SR__ s_107[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -62} }, 
};

SR__ s_108[] =
{
    { { REQ_TOKEN}, {  14} },                         
    { {       316}, { 135} }, // relational_statement 
    { {       263}, { 136} }, // FLOAT                
    { {       262}, { 137} }, // INTEGER              
    { {       264}, { 138} }, // DOUBLE               
    { {       317}, { 104} }, // arithmetic_expression
    { {       320}, { 105} }, // constant             
    { {       319}, { 106} }, // variable             
    { {       311}, { 107} }, // function_call        
    { {        40}, { 108} }, // '('                  
    { {        45}, { 109} }, // '-'                  
    { {       257}, { 110} }, // INTEGER_NUMBER       
    { {       259}, { 111} }, // FLOAT_NUMBER         
    { {       260}, {  84} }, // NAME                 
    { {         0}, {   0} },                         
};

SR__ s_109[] =
{
    { { REQ_TOKEN}, {  10} },                         
    { {       317}, { 139} }, // arithmetic_expression
    { {       320}, { 105} }, // constant             
    { {       319}, { 106} }, // variable             
    { {       311}, { 107} }, // function_call        
    { {        40}, { 108} }, // '('                  
    { {        45}, { 109} }, // '-'                  
    { {       257}, { 110} }, // INTEGER_NUMBER       
    { {       259}, { 111} }, // FLOAT_NUMBER         
    { {       260}, {  84} }, // NAME                 
    { {         0}, {   0} },                         
};

SR__ s_110[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -80} }, 
};

SR__ s_111[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -81} }, 
};

SR__ s_112[] =
{
    { { REQ_TOKEN}, {  11} },                         
    { {       316}, { 140} }, // relational_statement 
    { {       317}, { 104} }, // arithmetic_expression
    { {       320}, { 105} }, // constant             
    { {       319}, { 106} }, // variable             
    { {       311}, { 107} }, // function_call        
    { {        40}, { 108} }, // '('                  
    { {        45}, { 109} }, // '-'                  
    { {       257}, { 110} }, // INTEGER_NUMBER       
    { {       259}, { 111} }, // FLOAT_NUMBER         
    { {       260}, {  84} }, // NAME                 
    { {         0}, {   0} },                         
};

SR__ s_113[] =
{
    { { REQ_TOKEN}, {   2} },       
    { {        59}, { 141} }, // ';'
    { {         0}, {   0} },       
};

SR__ s_114[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -23} }, 
};

SR__ s_115[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -25} }, 
};

SR__ s_116[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -27} }, 
};

SR__ s_117[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -21} }, 
};

SR__ s_118[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -42} }, 
};

SR__ s_119[] =
{
    { { REQ_TOKEN}, {   8} },       
    { {        59}, { 142} }, // ';'
    { {       273}, { 125} }, // le 
    { {       275}, { 126} }, // ge 
    { {       274}, { 127} }, // gt 
    { {       272}, { 128} }, // lt 
    { {       271}, { 129} }, // eq 
    { {       270}, { 130} }, // ne 
    { {         0}, {   0} },       
};

SR__ s_120[] =
{
    { { REQ_TOKEN}, {   3} },       
    { {        41}, { 143} }, // ')'
    { {        44}, { 144} }, // ','
    { {         0}, {   0} },       
};

SR__ s_121[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -47} }, 
};

SR__ s_122[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -48} }, 
};

SR__ s_123[] =
{
    { { REQ_DEF}, {   7} },      
    { {     273}, { 125} }, // le
    { {     275}, { 126} }, // ge
    { {     274}, { 127} }, // gt
    { {     272}, { 128} }, // lt
    { {     271}, { 129} }, // eq
    { {     270}, { 130} }, // ne
    { {       0}, { -50} },      
};

SR__ s_124[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -38} }, 
};

SR__ s_125[] =
{
    { { REQ_TOKEN}, {  11} },                         
    { {       316}, { 145} }, // relational_statement 
    { {       317}, { 104} }, // arithmetic_expression
    { {       320}, { 105} }, // constant             
    { {       319}, { 106} }, // variable             
    { {       311}, { 107} }, // function_call        
    { {        40}, { 108} }, // '('                  
    { {        45}, { 109} }, // '-'                  
    { {       257}, { 110} }, // INTEGER_NUMBER       
    { {       259}, { 111} }, // FLOAT_NUMBER         
    { {       260}, {  84} }, // NAME                 
    { {         0}, {   0} },                         
};

SR__ s_126[] =
{
    { { REQ_TOKEN}, {  11} },                         
    { {       316}, { 146} }, // relational_statement 
    { {       317}, { 104} }, // arithmetic_expression
    { {       320}, { 105} }, // constant             
    { {       319}, { 106} }, // variable             
    { {       311}, { 107} }, // function_call        
    { {        40}, { 108} }, // '('                  
    { {        45}, { 109} }, // '-'                  
    { {       257}, { 110} }, // INTEGER_NUMBER       
    { {       259}, { 111} }, // FLOAT_NUMBER         
    { {       260}, {  84} }, // NAME                 
    { {         0}, {   0} },                         
};

SR__ s_127[] =
{
    { { REQ_TOKEN}, {  11} },                         
    { {       316}, { 147} }, // relational_statement 
    { {       317}, { 104} }, // arithmetic_expression
    { {       320}, { 105} }, // constant             
    { {       319}, { 106} }, // variable             
    { {       311}, { 107} }, // function_call        
    { {        40}, { 108} }, // '('                  
    { {        45}, { 109} }, // '-'                  
    { {       257}, { 110} }, // INTEGER_NUMBER       
    { {       259}, { 111} }, // FLOAT_NUMBER         
    { {       260}, {  84} }, // NAME                 
    { {         0}, {   0} },                         
};

SR__ s_128[] =
{
    { { REQ_TOKEN}, {  11} },                         
    { {       316}, { 148} }, // relational_statement 
    { {       317}, { 104} }, // arithmetic_expression
    { {       320}, { 105} }, // constant             
    { {       319}, { 106} }, // variable             
    { {       311}, { 107} }, // function_call        
    { {        40}, { 108} }, // '('                  
    { {        45}, { 109} }, // '-'                  
    { {       257}, { 110} }, // INTEGER_NUMBER       
    { {       259}, { 111} }, // FLOAT_NUMBER         
    { {       260}, {  84} }, // NAME                 
    { {         0}, {   0} },                         
};

SR__ s_129[] =
{
    { { REQ_TOKEN}, {  11} },                         
    { {       316}, { 149} }, // relational_statement 
    { {       317}, { 104} }, // arithmetic_expression
    { {       320}, { 105} }, // constant             
    { {       319}, { 106} }, // variable             
    { {       311}, { 107} }, // function_call        
    { {        40}, { 108} }, // '('                  
    { {        45}, { 109} }, // '-'                  
    { {       257}, { 110} }, // INTEGER_NUMBER       
    { {       259}, { 111} }, // FLOAT_NUMBER         
    { {       260}, {  84} }, // NAME                 
    { {         0}, {   0} },                         
};

SR__ s_130[] =
{
    { { REQ_TOKEN}, {  11} },                         
    { {       316}, { 150} }, // relational_statement 
    { {       317}, { 104} }, // arithmetic_expression
    { {       320}, { 105} }, // constant             
    { {       319}, { 106} }, // variable             
    { {       311}, { 107} }, // function_call        
    { {        40}, { 108} }, // '('                  
    { {        45}, { 109} }, // '-'                  
    { {       257}, { 110} }, // INTEGER_NUMBER       
    { {       259}, { 111} }, // FLOAT_NUMBER         
    { {       260}, {  84} }, // NAME                 
    { {         0}, {   0} },                         
};

SR__ s_131[] =
{
    { { REQ_TOKEN}, {  10} },                         
    { {       317}, { 151} }, // arithmetic_expression
    { {       320}, { 105} }, // constant             
    { {       319}, { 106} }, // variable             
    { {       311}, { 107} }, // function_call        
    { {        40}, { 108} }, // '('                  
    { {        45}, { 109} }, // '-'                  
    { {       257}, { 110} }, // INTEGER_NUMBER       
    { {       259}, { 111} }, // FLOAT_NUMBER         
    { {       260}, {  84} }, // NAME                 
    { {         0}, {   0} },                         
};

SR__ s_132[] =
{
    { { REQ_TOKEN}, {  10} },                         
    { {       317}, { 152} }, // arithmetic_expression
    { {       320}, { 105} }, // constant             
    { {       319}, { 106} }, // variable             
    { {       311}, { 107} }, // function_call        
    { {        40}, { 108} }, // '('                  
    { {        45}, { 109} }, // '-'                  
    { {       257}, { 110} }, // INTEGER_NUMBER       
    { {       259}, { 111} }, // FLOAT_NUMBER         
    { {       260}, {  84} }, // NAME                 
    { {         0}, {   0} },                         
};

SR__ s_133[] =
{
    { { REQ_TOKEN}, {  10} },                         
    { {       317}, { 153} }, // arithmetic_expression
    { {       320}, { 105} }, // constant             
    { {       319}, { 106} }, // variable             
    { {       311}, { 107} }, // function_call        
    { {        40}, { 108} }, // '('                  
    { {        45}, { 109} }, // '-'                  
    { {       257}, { 110} }, // INTEGER_NUMBER       
    { {       259}, { 111} }, // FLOAT_NUMBER         
    { {       260}, {  84} }, // NAME                 
    { {         0}, {   0} },                         
};

SR__ s_134[] =
{
    { { REQ_TOKEN}, {  10} },                         
    { {       317}, { 154} }, // arithmetic_expression
    { {       320}, { 105} }, // constant             
    { {       319}, { 106} }, // variable             
    { {       311}, { 107} }, // function_call        
    { {        40}, { 108} }, // '('                  
    { {        45}, { 109} }, // '-'                  
    { {       257}, { 110} }, // INTEGER_NUMBER       
    { {       259}, { 111} }, // FLOAT_NUMBER         
    { {       260}, {  84} }, // NAME                 
    { {         0}, {   0} },                         
};

SR__ s_135[] =
{
    { { REQ_TOKEN}, {   8} },       
    { {        41}, { 155} }, // ')'
    { {       273}, { 125} }, // le 
    { {       275}, { 126} }, // ge 
    { {       274}, { 127} }, // gt 
    { {       272}, { 128} }, // lt 
    { {       271}, { 129} }, // eq 
    { {       270}, { 130} }, // ne 
    { {         0}, {   0} },       
};

SR__ s_136[] =
{
    { { REQ_TOKEN}, {   2} },       
    { {        41}, { 156} }, // ')'
    { {         0}, {   0} },       
};

SR__ s_137[] =
{
    { { REQ_TOKEN}, {   2} },       
    { {        41}, { 157} }, // ')'
    { {         0}, {   0} },       
};

SR__ s_138[] =
{
    { { REQ_TOKEN}, {   2} },       
    { {        41}, { 158} }, // ')'
    { {         0}, {   0} },       
};

SR__ s_139[] =
{
    { { REQ_DEF}, {   3} },       
    { {      42}, { 133} }, // '*'
    { {      47}, { 134} }, // '/'
    { {       0}, { -73} },       
};

SR__ s_140[] =
{
    { { REQ_TOKEN}, {   8} },       
    { {        41}, { 159} }, // ')'
    { {       273}, { 125} }, // le 
    { {       275}, { 126} }, // ge 
    { {       274}, { 127} }, // gt 
    { {       272}, { 128} }, // lt 
    { {       271}, { 129} }, // eq 
    { {       270}, { 130} }, // ne 
    { {         0}, {   0} },       
};

SR__ s_141[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -52} }, 
};

SR__ s_142[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -78} }, 
};

SR__ s_143[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -46} }, 
};

SR__ s_144[] =
{
    { { REQ_TOKEN}, {  12} },                         
    { {       313}, { 160} }, // function_argument    
    { {       316}, { 123} }, // relational_statement 
    { {       317}, { 104} }, // arithmetic_expression
    { {       320}, { 105} }, // constant             
    { {       319}, { 106} }, // variable             
    { {       311}, { 107} }, // function_call        
    { {        40}, { 108} }, // '('                  
    { {        45}, { 109} }, // '-'                  
    { {       257}, { 110} }, // INTEGER_NUMBER       
    { {       259}, { 111} }, // FLOAT_NUMBER         
    { {       260}, {  84} }, // NAME                 
    { {         0}, {   0} },                         
};

SR__ s_145[] =
{
    { { REQ_DEF}, {   1} }, 
    { {       0}, { -54} }, 
};

SR__ s_146[] =
{
    { { REQ_DEF}, {   1} }, 
    { {       0}, { -55} }, 
};

SR__ s_147[] =
{
    { { REQ_DEF}, {   1} }, 
    { {       0}, { -56} }, 
};

SR__ s_148[] =
{
    { { REQ_DEF}, {   1} }, 
    { {       0}, { -57} }, 
};

SR__ s_149[] =
{
    { { REQ_DEF}, {   5} },      
    { {     273}, { 125} }, // le
    { {     275}, { 126} }, // ge
    { {     274}, { 127} }, // gt
    { {     272}, { 128} }, // lt
    { {       0}, { -58} },      
};

SR__ s_150[] =
{
    { { REQ_DEF}, {   5} },      
    { {     273}, { 125} }, // le
    { {     275}, { 126} }, // ge
    { {     274}, { 127} }, // gt
    { {     272}, { 128} }, // lt
    { {       0}, { -59} },      
};

SR__ s_151[] =
{
    { { REQ_DEF}, {   3} },       
    { {      42}, { 133} }, // '*'
    { {      47}, { 134} }, // '/'
    { {       0}, { -74} },       
};

SR__ s_152[] =
{
    { { REQ_DEF}, {   3} },       
    { {      42}, { 133} }, // '*'
    { {      47}, { 134} }, // '/'
    { {       0}, { -75} },       
};

SR__ s_153[] =
{
    { { REQ_DEF}, {   1} }, 
    { {       0}, { -76} }, 
};

SR__ s_154[] =
{
    { { REQ_DEF}, {   1} }, 
    { {       0}, { -77} }, 
};

SR__ s_155[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -63} }, 
};

SR__ s_156[] =
{
    { { REQ_TOKEN}, {   5} },                 
    { {       311}, { 161} }, // function_call
    { {       319}, { 162} }, // variable     
    { {        40}, { 163} }, // '('          
    { {       260}, {  84} }, // NAME         
    { {         0}, {   0} },                 
};

SR__ s_157[] =
{
    { { REQ_TOKEN}, {   5} },                 
    { {       311}, { 164} }, // function_call
    { {       319}, { 165} }, // variable     
    { {        40}, { 166} }, // '('          
    { {       260}, {  84} }, // NAME         
    { {         0}, {   0} },                 
};

SR__ s_158[] =
{
    { { REQ_TOKEN}, {   5} },                 
    { {       311}, { 167} }, // function_call
    { {       319}, { 168} }, // variable     
    { {        40}, { 169} }, // '('          
    { {       260}, {  84} }, // NAME         
    { {         0}, {   0} },                 
};

SR__ s_159[] =
{
    { { REQ_TOKEN}, {   3} },                  
    { {       315}, { 170} }, // goto_statement
    { {       268}, {  87} }, // GOTO          
    { {         0}, {   0} },                  
};

SR__ s_160[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -49} }, 
};

SR__ s_161[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -64} }, 
};

SR__ s_162[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -67} }, 
};

SR__ s_163[] =
{
    { { REQ_TOKEN}, {  11} },                         
    { {       316}, { 171} }, // relational_statement 
    { {       317}, { 104} }, // arithmetic_expression
    { {       320}, { 105} }, // constant             
    { {       319}, { 106} }, // variable             
    { {       311}, { 107} }, // function_call        
    { {        40}, { 108} }, // '('                  
    { {        45}, { 109} }, // '-'                  
    { {       257}, { 110} }, // INTEGER_NUMBER       
    { {       259}, { 111} }, // FLOAT_NUMBER         
    { {       260}, {  84} }, // NAME                 
    { {         0}, {   0} },                         
};

SR__ s_164[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -65} }, 
};

SR__ s_165[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -68} }, 
};

SR__ s_166[] =
{
    { { REQ_TOKEN}, {  10} },                         
    { {       317}, { 172} }, // arithmetic_expression
    { {       320}, { 105} }, // constant             
    { {       319}, { 106} }, // variable             
    { {       311}, { 107} }, // function_call        
    { {        40}, { 108} }, // '('                  
    { {        45}, { 109} }, // '-'                  
    { {       257}, { 110} }, // INTEGER_NUMBER       
    { {       259}, { 111} }, // FLOAT_NUMBER         
    { {       260}, {  84} }, // NAME                 
    { {         0}, {   0} },                         
};

SR__ s_167[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -66} }, 
};

SR__ s_168[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -69} }, 
};

SR__ s_169[] =
{
    { { REQ_TOKEN}, {  11} },                         
    { {       316}, { 173} }, // relational_statement 
    { {       317}, { 104} }, // arithmetic_expression
    { {       320}, { 105} }, // constant             
    { {       319}, { 106} }, // variable             
    { {       311}, { 107} }, // function_call        
    { {        40}, { 108} }, // '('                  
    { {        45}, { 109} }, // '-'                  
    { {       257}, { 110} }, // INTEGER_NUMBER       
    { {       259}, { 111} }, // FLOAT_NUMBER         
    { {       260}, {  84} }, // NAME                 
    { {         0}, {   0} },                         
};

SR__ s_170[] =
{
    { { REQ_TOKEN}, {   2} },        
    { {       267}, { 174} }, // ELSE
    { {         0}, {   0} },        
};

SR__ s_171[] =
{
    { { REQ_TOKEN}, {   8} },       
    { {        41}, { 175} }, // ')'
    { {       273}, { 125} }, // le 
    { {       275}, { 126} }, // ge 
    { {       274}, { 127} }, // gt 
    { {       272}, { 128} }, // lt 
    { {       271}, { 129} }, // eq 
    { {       270}, { 130} }, // ne 
    { {         0}, {   0} },       
};

SR__ s_172[] =
{
    { { REQ_TOKEN}, {   6} },       
    { {        41}, { 176} }, // ')'
    { {        43}, { 131} }, // '+'
    { {        45}, { 132} }, // '-'
    { {        42}, { 133} }, // '*'
    { {        47}, { 134} }, // '/'
    { {         0}, {   0} },       
};

SR__ s_173[] =
{
    { { REQ_TOKEN}, {   8} },       
    { {        41}, { 177} }, // ')'
    { {       273}, { 125} }, // le 
    { {       275}, { 126} }, // ge 
    { {       274}, { 127} }, // gt 
    { {       272}, { 128} }, // lt 
    { {       271}, { 129} }, // eq 
    { {       270}, { 130} }, // ne 
    { {         0}, {   0} },       
};

SR__ s_174[] =
{
    { { REQ_TOKEN}, {   3} },                  
    { {       315}, { 178} }, // goto_statement
    { {       268}, {  87} }, // GOTO          
    { {         0}, {   0} },                  
};

SR__ s_175[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -71} }, 
};

SR__ s_176[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -70} }, 
};

SR__ s_177[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -72} }, 
};

SR__ s_178[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -51} }, 
};


// State array:
SR__ *s_state[] =
{
  s_0,  s_1,  s_2,  s_3,  s_4,  s_5,  s_6,  s_7,  s_8,  s_9,
  s_10,  s_11,  s_12,  s_13,  s_14,  s_15,  s_16,  s_17,  s_18,  s_19,
  s_20,  s_21,  s_22,  s_23,  s_24,  s_25,  s_26,  s_27,  s_28,  s_29,
  s_30,  s_31,  s_32,  s_33,  s_34,  s_35,  s_36,  s_37,  s_38,  s_39,
  s_40,  s_41,  s_42,  s_43,  s_44,  s_45,  s_46,  s_47,  s_48,  s_49,
  s_50,  s_51,  s_52,  s_53,  s_54,  s_55,  s_56,  s_57,  s_58,  s_59,
  s_60,  s_61,  s_62,  s_63,  s_64,  s_65,  s_66,  s_67,  s_68,  s_69,
  s_70,  s_71,  s_72,  s_73,  s_74,  s_75,  s_76,  s_77,  s_78,  s_79,
  s_80,  s_81,  s_82,  s_83,  s_84,  s_85,  s_86,  s_87,  s_88,  s_89,
  s_90,  s_91,  s_92,  s_93,  s_94,  s_95,  s_96,  s_97,  s_98,  s_99,
  s_100,  s_101,  s_102,  s_103,  s_104,  s_105,  s_106,  s_107,  s_108,  s_109,
  s_110,  s_111,  s_112,  s_113,  s_114,  s_115,  s_116,  s_117,  s_118,  s_119,
  s_120,  s_121,  s_122,  s_123,  s_124,  s_125,  s_126,  s_127,  s_128,  s_129,
  s_130,  s_131,  s_132,  s_133,  s_134,  s_135,  s_136,  s_137,  s_138,  s_139,
  s_140,  s_141,  s_142,  s_143,  s_144,  s_145,  s_146,  s_147,  s_148,  s_149,
  s_150,  s_151,  s_152,  s_153,  s_154,  s_155,  s_156,  s_157,  s_158,  s_159,
  s_160,  s_161,  s_162,  s_163,  s_164,  s_165,  s_166,  s_167,  s_168,  s_169,
  s_170,  s_171,  s_172,  s_173,  s_174,  s_175,  s_176,  s_177,  s_178,
};

} // anonymous namespace ends



// If the parsing function call uses arguments, then provide an overloaded
// function.  The code below doesn't rely on parameters, so no arguments are
// required.  Furthermore, parse uses a function try block to allow us to do
// ACCEPT and ABORT from anywhere, even from within members called by actions,
// simply throwing the appropriate exceptions.

ParserBase::ParserBase()
:
    d_stackIdx__(-1),
    // $insert debuginit
    d_debug__(false),
    d_nErrors__(0),
    // $insert requiredtokens
    d_requiredTokens__(0),
    d_acceptedTokens__(d_requiredTokens__),
    d_token__(_UNDETERMINED_),
    d_nextToken__(_UNDETERMINED_)
{}


void ParserBase::clearin()
{
    d_token__ = d_nextToken__ = _UNDETERMINED_;
}

void ParserBase::push__(size_t state)
{
    if (static_cast<size_t>(d_stackIdx__ + 1) == d_stateStack__.size())
    {
        size_t newSize = d_stackIdx__ + STACK_EXPANSION;
        d_stateStack__.resize(newSize);
        d_valueStack__.resize(newSize);
    }
    ++d_stackIdx__;
    d_stateStack__[d_stackIdx__] = d_state__ = state;
    *(d_vsp__ = &d_valueStack__[d_stackIdx__]) = d_val__;
}

void ParserBase::popToken__()
{
    d_token__ = d_nextToken__;

    d_val__ = d_nextVal__;
    d_nextVal__ = STYPE__();

    d_nextToken__ = _UNDETERMINED_;
}
     
void ParserBase::pushToken__(int token)
{
    d_nextToken__ = d_token__;
    d_nextVal__ = d_val__;
    d_token__ = token;
}
     
void ParserBase::pop__(size_t count)
{
    if (d_stackIdx__ < static_cast<int>(count))
    {
        ABORT();
    }

    d_stackIdx__ -= count;
    d_state__ = d_stateStack__[d_stackIdx__];
    d_vsp__ = &d_valueStack__[d_stackIdx__];
}

inline size_t ParserBase::top__() const
{
    return d_stateStack__[d_stackIdx__];
}

void Parser::executeAction(int production)
{
    if (d_token__ != _UNDETERMINED_)
        pushToken__(d_token__);     // save an already available token

                                    // save default non-nested block $$
    if (int size = s_productionInfo[production].d_size)
        d_val__ = d_vsp__[1 - size];

    switch (production)
    {
        // $insert actioncases
        
        case 2:
        d_val__ = d_vsp__[-1];
        {
         program_object.set_global_table(*d_vsp__[-1].symbol_table);
         }
        break;

        case 4:
        d_val__ = d_vsp__[0];
        {
         program_object.set_global_table(*d_vsp__[0].symbol_table);
         }
        break;

        case 9:
        {
         current_procedure = program_object.get_procedure_map(*d_vsp__[-3].string_value);
         }
        break;

        case 10:
        {
         if(*d_vsp__[-2].string_value == "main"){
         current_procedure = new Procedure(void_data_type, *d_vsp__[-2].string_value, *(new Symbol_Table));
         program_object.set_procedure_map(*current_procedure);
         }
         current_procedure = program_object.get_procedure_map(*d_vsp__[-2].string_value);
         }
        break;

        case 11:
        {
         
         
         
         
         
         
         
         current_procedure->set_basic_block_list(*d_vsp__[-1].basic_block_list);
         if(program_object.max_bb_call > program_object.max_bb){
         char error[200];
         sprintf(error , "bb %d doesn't exist" , program_object.max_bb_call);
         string str(error);
         report_error(str, NOLINE);
         }
         delete d_vsp__[-1].basic_block_list;
         }
        break;

        case 12:
        d_val__ = d_vsp__[-1];
        {
         current_procedure->append_local_list(*d_vsp__[0].symbol_table);
         delete d_vsp__[0].symbol_table;
         }
        break;

        case 13:
        {
         
         
         
         
         
         
         
         
         current_procedure->set_basic_block_list(*d_vsp__[-1].basic_block_list);
         if(program_object.max_bb_call > program_object.max_bb){
         char error[200];
         sprintf(error , "bb %d doesn't exist" , program_object.max_bb_call);
         string str(error);
         report_error(str, NOLINE);
         }
         delete d_vsp__[-1].basic_block_list;
         }
        break;

        case 16:
        {
         int line = get_line_number();
         program_object.variable_in_proc_map_check(d_vsp__[0].symbol_entry->get_variable_name(), line);
         string var_name = d_vsp__[0].symbol_entry->get_variable_name();
         if (current_procedure && current_procedure->get_proc_name() == var_name)
         {
         int line = get_line_number();
         report_error("Variable name cannot be same as procedure name", line);
         }
         d_val__.symbol_table = new Symbol_Table();
         d_val__.symbol_table->push_symbol(d_vsp__[0].symbol_entry);
         }
        break;

        case 17:
        {
         
         
         int line = get_line_number();
         program_object.variable_in_proc_map_check(d_vsp__[0].symbol_entry->get_variable_name(), line);
         string var_name = d_vsp__[0].symbol_entry->get_variable_name();
         if (current_procedure && current_procedure->get_proc_name() == var_name)
         {
         int line = get_line_number();
         report_error("Variable name cannot be same as procedure name", line);
         }
         if (d_vsp__[-1].symbol_table != NULL)
         {
         if(d_vsp__[-1].symbol_table->variable_in_symbol_list_check(var_name))
         {
         int line = get_line_number();
         report_error("Variable is declared twice", line);
         }
         d_val__.symbol_table = d_vsp__[-1].symbol_table;
         }
         else
         d_val__.symbol_table = new Symbol_Table();
         d_val__.symbol_table->push_symbol(d_vsp__[0].symbol_entry);
         }
        break;

        case 18:
        {
         
         
         d_val__.symbol_entry = new Symbol_Table_Entry(*d_vsp__[-1].string_value, int_data_type);
         delete d_vsp__[-1].string_value;
         }
        break;

        case 19:
        {
         
         
         d_val__.symbol_entry = new Symbol_Table_Entry(*d_vsp__[-1].string_value, float_data_type);
         delete d_vsp__[-1].string_value;
         }
        break;

        case 20:
        {
         d_val__.symbol_entry = new Symbol_Table_Entry(*d_vsp__[-1].string_value, float_data_type);
         delete d_vsp__[-1].string_value; 
         }
        break;

        case 21:
        {
         Procedure * p = new Procedure(void_data_type, *d_vsp__[-4].string_value, *d_vsp__[-2].symbol_table);
         program_object.set_procedure_map(*p);
         }
        break;

        case 22:
        {
         Procedure * p = new Procedure(void_data_type, *d_vsp__[-3].string_value, *(new Symbol_Table()));
         program_object.set_procedure_map(*p);
         }
        break;

        case 23:
        {
         Procedure * p = new Procedure(int_data_type, *d_vsp__[-4].string_value, *d_vsp__[-2].symbol_table);
         program_object.set_procedure_map(*p);
         }
        break;

        case 24:
        {
         Procedure * p = new Procedure(int_data_type, *d_vsp__[-3].string_value, *(new Symbol_Table()));
         program_object.set_procedure_map(*p);
         }
        break;

        case 25:
        {
         Procedure * p = new Procedure(float_data_type, *d_vsp__[-4].string_value, *d_vsp__[-2].symbol_table);
         program_object.set_procedure_map(*p);
         }
        break;

        case 26:
        {
         Procedure * p = new Procedure(float_data_type, *d_vsp__[-3].string_value, *(new Symbol_Table()));
         program_object.set_procedure_map(*p);
         }
        break;

        case 27:
        {
         Procedure * p = new Procedure(float_data_type, *d_vsp__[-4].string_value, *d_vsp__[-2].symbol_table);
         program_object.set_procedure_map(*p);
         }
        break;

        case 28:
        {
         Procedure * p = new Procedure(float_data_type, *d_vsp__[-3].string_value, *(new Symbol_Table()));
         program_object.set_procedure_map(*p);
         }
        break;

        case 29:
        {
         d_val__.symbol_table = new Symbol_Table();
         d_val__.symbol_table->push_symbol(d_vsp__[0].symbol_entry);
         }
        break;

        case 30:
        {
         if (d_vsp__[-2].symbol_table != NULL)
         {
         
        
         d_val__.symbol_table = d_vsp__[-2].symbol_table;
         }
         else
         d_val__.symbol_table = new Symbol_Table();
         d_val__.symbol_table->push_symbol(d_vsp__[0].symbol_entry);
         }
        break;

        case 31:
        {
         d_val__.symbol_entry = new Symbol_Table_Entry(*d_vsp__[0].string_value, int_data_type);
         delete d_vsp__[0].string_value;
         }
        break;

        case 32:
        {
         d_val__.symbol_entry = new Symbol_Table_Entry(*d_vsp__[0].string_value, float_data_type);
         delete d_vsp__[0].string_value;
         }
        break;

        case 33:
        {
         d_val__.symbol_entry = new Symbol_Table_Entry(*d_vsp__[0].string_value, float_data_type);
         delete d_vsp__[0].string_value;
         }
        break;

        case 34:
        {
         if (!d_vsp__[0].basic_block)
         {
         int line = get_line_number();
         report_error("Basic block doesn't exist", line);
         }
         bb_strictly_increasing_order_check(d_val__.basic_block_list, d_vsp__[0].basic_block->get_bb_number());
         d_val__.basic_block_list = d_vsp__[-1].basic_block_list;
         d_val__.basic_block_list->push_back(d_vsp__[0].basic_block);
         }
        break;

        case 35:
        {
         if (!d_vsp__[0].basic_block)
         {
         int line = get_line_number();
         report_error("Basic block doesn't exist", line);
         }
         d_val__.basic_block_list = new list<Basic_Block *>;
         d_val__.basic_block_list->push_back(d_vsp__[0].basic_block);
         }
        break;

        case 36:
        {
        
        
        
        
        
         
         
         string bbl(*d_vsp__[-2].string_value);
         if(atoi(bbl.substr(4, bbl.length()-1).c_str()) > program_object.max_bb)
         program_object.max_bb = atoi(bbl.substr(4, bbl.length()-1).c_str());
         if (atoi(bbl.substr(4, bbl.length()-1).c_str()) < 2)
         {
         int line = get_line_number();
         report_error("Illegal basic block lable", line);
         }
         
         if (d_vsp__[0].ast_list != NULL)
         d_val__.basic_block = new Basic_Block(atoi(bbl.substr(4, bbl.length()-1).c_str()), *d_vsp__[0].ast_list);
         else
         {
         list<Ast *> * ast_list = new list<Ast *>;
         d_val__.basic_block = new Basic_Block(atoi(bbl.substr(4, bbl.length()-1).c_str()), *ast_list);
         }
         delete d_vsp__[0].ast_list;
         }
        break;

        case 37:
        {
         d_val__.ast = new Return_Ast(NULL);
         }
        break;

        case 38:
        {
         d_val__.ast = new Return_Ast(d_vsp__[-1].ast);
         }
        break;

        case 39:
        {
         d_val__.ast_list = new list < Ast * >;
         d_val__.ast_list->push_front(d_vsp__[0].ast);
         }
        break;

        case 40:
        {
         d_val__.ast_list = new list < Ast * >;
         d_val__.ast_list->push_front(d_vsp__[-1].ast);
         }
        break;

        case 41:
        {
         d_val__.ast_list = d_vsp__[0].ast_list;
         d_val__.ast_list->push_front(d_vsp__[-1].ast);
         }
        break;

        case 42:
        {
         d_val__.ast_list = d_vsp__[0].ast_list;
         d_val__.ast_list->push_front(d_vsp__[-2].ast);
         }
        break;

        case 43:
        {
         d_val__.ast_list = new list < Ast * >;
         d_val__.ast_list->push_front(d_vsp__[0].ast);;
         }
        break;

        case 44:
        {
         d_val__.ast_list = new list < Ast * >;
         d_val__.ast_list->push_front(d_vsp__[0].ast);
         }
        break;

        case 45:
        {
         d_val__.ast_list = new list < Ast * >;
         d_val__.ast_list->push_front(d_vsp__[0].ast);
         }
        break;

        case 46:
        {
         d_val__.ast = new Call_Ast(d_vsp__[-1].ast_list,program_object.get_procedure_map(*d_vsp__[-3].string_value));
         }
        break;

        case 47:
        {
         d_val__.ast = new Call_Ast(NULL,program_object.get_procedure_map(*d_vsp__[-2].string_value));
         }
        break;

        case 48:
        {
         d_val__.ast_list = new list < Ast * >;
         d_val__.ast_list->push_back(d_vsp__[0].ast);
         }
        break;

        case 49:
        {
         d_val__.ast_list->push_back(d_vsp__[0].ast);
         }
        break;

        case 50:
        {
         d_val__.ast = d_vsp__[0].ast;
         }
        break;

        case 51:
        {
         d_val__.ast = new If_Else_Ast(d_vsp__[-4].ast, d_vsp__[-2].ast, d_vsp__[0].ast);
         }
        break;

        case 52:
        {
         string str(*d_vsp__[-1].string_value);
         if(atoi(str.substr(4, str.length()-1).c_str()) > program_object.max_bb_call)
         program_object.max_bb_call = atoi(str.substr(4, str.length()-1).c_str());
         d_val__.ast = new Goto_Ast(atoi(str.substr(4, str.length()-1).c_str()));
         }
        break;

        case 53:
        {
         d_val__.ast = new Relational_Ast(d_vsp__[0].ast);
         }
        break;

        case 54:
        {
         
         d_val__.ast = new Relational_Ast(d_vsp__[-2].ast, d_vsp__[0].ast, LE);
         int line = get_line_number();
         d_val__.ast->check_ast(line);
         }
        break;

        case 55:
        {
         
         d_val__.ast = new Relational_Ast(d_vsp__[-2].ast, d_vsp__[0].ast, GE);
         int line = get_line_number();
         d_val__.ast->check_ast(line);
         }
        break;

        case 56:
        {
         
         d_val__.ast = new Relational_Ast(d_vsp__[-2].ast, d_vsp__[0].ast, GT);
         int line = get_line_number();
         d_val__.ast->check_ast(line);
         }
        break;

        case 57:
        {
         
         d_val__.ast = new Relational_Ast(d_vsp__[-2].ast, d_vsp__[0].ast, LT);
         int line = get_line_number();
         d_val__.ast->check_ast(line);
         }
        break;

        case 58:
        {
         
         d_val__.ast = new Relational_Ast(d_vsp__[-2].ast, d_vsp__[0].ast, EQ);
         int line = get_line_number();
         d_val__.ast->check_ast(line);
         }
        break;

        case 59:
        {
         
         d_val__.ast = new Relational_Ast(d_vsp__[-2].ast, d_vsp__[0].ast, NE);
         int line = get_line_number();
         d_val__.ast->check_ast(line);
         }
        break;

        case 60:
        {
         d_val__.ast = d_vsp__[0].ast;
         }
        break;

        case 61:
        {
         d_val__.ast = d_vsp__[0].ast;
         }
        break;

        case 62:
        {
         }
        break;

        case 63:
        {
         d_val__.ast = d_vsp__[-1].ast;
         }
        break;

        case 64:
        {
         d_val__.ast = new Type_Cast_Ast(d_vsp__[0].ast, float_data_type);
         }
        break;

        case 65:
        {
         d_val__.ast = new Type_Cast_Ast(d_vsp__[0].ast, int_data_type);
         }
        break;

        case 66:
        {
         d_val__.ast = new Type_Cast_Ast(d_vsp__[0].ast, float_data_type);
         }
        break;

        case 67:
        {
         d_val__.ast = new Type_Cast_Ast(d_vsp__[0].ast, float_data_type);
         }
        break;

        case 68:
        {
         d_val__.ast = new Type_Cast_Ast(d_vsp__[0].ast, int_data_type);
         }
        break;

        case 69:
        {
         d_val__.ast = new Type_Cast_Ast(d_vsp__[0].ast, float_data_type);
         }
        break;

        case 70:
        {
         d_val__.ast = new Type_Cast_Ast(d_vsp__[-1].ast, int_data_type);
         }
        break;

        case 71:
        {
         d_val__.ast = new Type_Cast_Ast(d_vsp__[-1].ast, float_data_type);
         }
        break;

        case 72:
        {
         d_val__.ast = new Type_Cast_Ast(d_vsp__[-1].ast, float_data_type);
         }
        break;

        case 73:
        {
         d_val__.ast = new Unary_Ast(d_vsp__[0].ast);
         }
        break;

        case 74:
        {
         d_val__.ast = new Plus_Ast(d_vsp__[-2].ast, d_vsp__[0].ast);
         int line = get_line_number();
         d_val__.ast->check_ast(line);
         }
        break;

        case 75:
        {
         d_val__.ast = new Minus_Ast(d_vsp__[-2].ast, d_vsp__[0].ast);
         int line = get_line_number();
         d_val__.ast->check_ast(line);
         }
        break;

        case 76:
        {
         d_val__.ast = new Multiplication_Ast(d_vsp__[-2].ast, d_vsp__[0].ast);
         int line = get_line_number();
         d_val__.ast->check_ast(line);
         }
        break;

        case 77:
        {
         d_val__.ast = new Division_Ast(d_vsp__[-2].ast, d_vsp__[0].ast);
         int line = get_line_number();
         d_val__.ast->check_ast(line);
         }
        break;

        case 78:
        {
         d_val__.ast = new Assignment_Ast(d_vsp__[-3].ast, d_vsp__[-1].ast);
         int line = get_line_number();
         
         d_val__.ast->check_ast(line);
         }
        break;

        case 79:
        {
        
         Symbol_Table_Entry var_table_entry;
         if (current_procedure->variable_in_symbol_list_check(*d_vsp__[0].string_value))
         var_table_entry = current_procedure->get_symbol_table_entry(*d_vsp__[0].string_value);
         else if (program_object.variable_in_symbol_list_check(*d_vsp__[0].string_value))
         var_table_entry = program_object.get_symbol_table_entry(*d_vsp__[0].string_value);
         else
         {
         int line = get_line_number();
         report_error("Variable has not been declared", line);
         }
         
         d_val__.ast = new Name_Ast(*d_vsp__[0].string_value, var_table_entry);
         delete d_vsp__[0].string_value;
         }
        break;

        case 80:
        {
         Value_Type vt;
         vt.i = d_vsp__[0].integer_value;
         d_val__.ast = new Number_Ast(vt, int_data_type);
         }
        break;

        case 81:
        {
         Value_Type vt;
         string str(*d_vsp__[0].string_value);
         vt.f = (float)atof(str.c_str());
         
         d_val__.ast = new Number_Ast(vt, float_data_type);
         }
        break;

    }
}

inline void ParserBase::reduce__(PI__ const &pi)
{
    d_token__ = pi.d_nonTerm;
    pop__(pi.d_size);

}

// If d_token__ is _UNDETERMINED_ then if d_nextToken__ is _UNDETERMINED_ another
// token is obtained from lex(). Then d_nextToken__ is assigned to d_token__.
void Parser::nextToken()
{
    if (d_token__ != _UNDETERMINED_)        // no need for a token: got one
        return;                             // already

    if (d_nextToken__ != _UNDETERMINED_)
    {
        popToken__();                       // consume pending token
    }
    else
    {
        ++d_acceptedTokens__;               // accept another token (see
                                            // errorRecover())
        d_token__ = lex();
        if (d_token__ <= 0)
            d_token__ = _EOF_;
    }
    print();
}

// if the final transition is negative, then we should reduce by the rule
// given by its positive value. Note that the `recovery' parameter is only
// used with the --debug option
int Parser::lookup(bool recovery)
{
    // $insert threading
    SR__ *sr = s_state[d_state__];        // get the appropriate state-table
    int lastIdx = sr->d_lastIdx;        // sentinel-index in the SR__ array

    SR__ *lastElementPtr = sr + lastIdx;
    SR__ *elementPtr = sr + 1;            // start the search at s_xx[1]

    lastElementPtr->d_token = d_token__;// set search-token

    while (elementPtr->d_token != d_token__)
        ++elementPtr;

    if (elementPtr == lastElementPtr)   // reached the last element
    {
        if (elementPtr->d_action < 0)   // default reduction
        {
            return elementPtr->d_action;                
        }

        // No default reduction, so token not found, so error.
        throw UNEXPECTED_TOKEN__;
    }

    // not at the last element: inspect the nature of the action
    // (< 0: reduce, 0: ACCEPT, > 0: shift)

    int action = elementPtr->d_action;


    return action;
}

    // When an error has occurred, pop elements off the stack until the top
    // state has an error-item. If none is found, the default recovery
    // mode (which is to abort) is activated. 
    //
    // If EOF is encountered without being appropriate for the current state,
    // then the error recovery will fall back to the default recovery mode.
    // (i.e., parsing terminates)
void Parser::errorRecovery()
try
{
    if (d_acceptedTokens__ >= d_requiredTokens__)// only generate an error-
    {                                           // message if enough tokens 
        ++d_nErrors__;                          // were accepted. Otherwise
        error("Syntax error");                  // simply skip input

    }


    // get the error state
    while (not (s_state[top__()][0].d_type & ERR_ITEM))
    {
        pop__();
    }

    // In the error state, lookup a token allowing us to proceed.
    // Continuation may be possible following multiple reductions,
    // but eventuall a shift will be used, requiring the retrieval of
    // a terminal token. If a retrieved token doesn't match, the catch below 
    // will ensure the next token is requested in the while(true) block
    // implemented below:

    int lastToken = d_token__;                  // give the unexpected token a
                                                // chance to be processed
                                                // again.

    pushToken__(_error_);                       // specify _error_ as next token
    push__(lookup(true));                       // push the error state

    d_token__ = lastToken;                      // reactivate the unexpected
                                                // token (we're now in an
                                                // ERROR state).

    bool gotToken = true;                       // the next token is a terminal

    while (true)
    {
        try
        {
            if (s_state[d_state__]->d_type & REQ_TOKEN)
            {
                gotToken = d_token__ == _UNDETERMINED_;
                nextToken();                    // obtain next token
            }
            
            int action = lookup(true);

            if (action > 0)                 // push a new state
            {
                push__(action);
                popToken__();

                if (gotToken)
                {

                    d_acceptedTokens__ = 0;
                    return;
                }
            }
            else if (action < 0)
            {
                // no actions executed on recovery but save an already 
                // available token:
                if (d_token__ != _UNDETERMINED_)
                    pushToken__(d_token__);
 
                                            // next token is the rule's LHS
                reduce__(s_productionInfo[-action]); 
            }
            else
                ABORT();                    // abort when accepting during
                                            // error recovery
        }
        catch (...)
        {
            if (d_token__ == _EOF_)
                ABORT();                    // saw inappropriate _EOF_
                      
            popToken__();                   // failing token now skipped
        }
    }
}
catch (ErrorRecovery__)       // This is: DEFAULT_RECOVERY_MODE
{
    ABORT();
}

    // The parsing algorithm:
    // Initially, state 0 is pushed on the stack, and d_token__ as well as
    // d_nextToken__ are initialized to _UNDETERMINED_. 
    //
    // Then, in an eternal loop:
    //
    //  1. If a state does not have REQ_TOKEN no token is assigned to
    //     d_token__. If the state has REQ_TOKEN, nextToken() is called to
    //      determine d_nextToken__ and d_token__ is set to
    //     d_nextToken__. nextToken() will not call lex() unless d_nextToken__ is 
    //     _UNDETERMINED_. 
    //
    //  2. lookup() is called: 
    //     d_token__ is stored in the final element's d_token field of the
    //     state's SR_ array. 
    //
    //  3. The current token is looked up in the state's SR_ array
    //
    //  4. Depending on the result of the lookup() function the next state is
    //     shifted on the parser's stack, a reduction by some rule is applied,
    //     or the parsing function returns ACCEPT(). When a reduction is
    //     called for, any action that may have been defined for that
    //     reduction is executed.
    //
    //  5. An error occurs if d_token__ is not found, and the state has no
    //     default reduction. Error handling was described at the top of this
    //     file.

int Parser::parse()
try 
{
    push__(0);                              // initial state
    clearin();                              // clear the tokens.

    while (true)
    {
        try
        {
            if (s_state[d_state__]->d_type & REQ_TOKEN)
                nextToken();                // obtain next token


            int action = lookup(false);     // lookup d_token__ in d_state__

            if (action > 0)                 // SHIFT: push a new state
            {
                push__(action);
                popToken__();               // token processed
            }
            else if (action < 0)            // REDUCE: execute and pop.
            {
                executeAction(-action);
                                            // next token is the rule's LHS
                reduce__(s_productionInfo[-action]); 
            }
            else 
                ACCEPT();
        }
        catch (ErrorRecovery__)
        {
            errorRecovery();
        }
    }
}
catch (Return__ retValue)
{
    return retValue;
}

